### ISSUE TITLE
Problem with Filter on Navigation Property

### ISSUE THREAD

**Issue by Xafa** [jcachat/EntityFramework.DynamicFilters#100]
Hi,

thanks for your great work.
But unfortunetly i get a Error when setting a filter to a navigation property and use a where-clause to a parent of this type.
It works fine if the filter does not use the navigation property or the query does not use the where clause (or if i am querying T_TABLE_B directly).
My Entities have a base class using TPC and i am using Oracle-DB if this matters.
Example with Exception:

Filter:
modelBuilder.Filter("FilterName", (T_TABLE_B b) => b.TABLE_C.STATUS_ID == EStatus.Aktiv);

Query:
var result = DataContext.Set<T_TABLE_A>().AsQueryable().Where(a => a.TABLE_BS.Any()).ToList();

throws Exception:
Property TABLE_C not found in Entity Type T_TABLE_B

StackTrace:
bei EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMember(MemberExpression node)
   bei System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   bei EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMember(MemberExpression node)
   bei System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   bei EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitUnary(UnaryExpression node)
   bei System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   bei EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   bei System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   bei System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   bei System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   bei EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, DbContext dbContext, DataSpace dataSpace)
   bei EntityFramework.DynamicFilters.DynamicFilterQueryVisitorSSpace.BuildFilterExpressionWithDynamicFilters(String entityName, IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   bei EntityFramework.DynamicFilters.DynamicFilterQueryVisitorSSpace.Visit(DbScanExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbJoinExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitUnary(DbUnaryExpression expression, Func`2 callback)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbIsEmptyExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbIsEmptyExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitUnary(DbUnaryExpression expression, Func`2 callback)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbNotExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbNotExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   bei System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   bei System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   bei EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   bei System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   bei System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)

It would be nice if you can look at this, and maybe show me a workaround?

Best Regards,
Xafa

**Comment by jcachat** [comment]
Oracle may be a factor here as it does not (or did not) support the EF DbExpression.Element() method because Oracle lacked support for the "apply" command.  That may have been fixed in Oracle 12c but I would need to re-test.  Because of that issue and the versions I needed to support at the time, there is some special handling needed which prevents some of the navigation property filtering.

So 2 things I need:
1) What version of Oracle server & client library (EF provider) are you using
2) Can you post the full code of your models (or at least the relevant portions).  Since you say you are using TPC, I need to make sure I replicate your models correctly in a unit test or I may not be able to reproduce the problem.

**Comment by Xafa** [comment]
Hi jcachat,
thanks for your reply. I tried a little bit on my own and i got this results:
It works fine on MS SQL Server, so this is an Oracle problem and with Oracle i got the same exception even without a base entity class, so this has nothing to do with it.

I am using Oracle 12c1 and the following libraries:
Oracle.ManagedDataAccess v12.1.24160719
Oracle.ManagedDataAccess.EntityFramework v12.1.2400

I attached you a sample project, i hope this helps you to reproduce the problem:
[EfDynamicFilter.zip](https://github.com/jcachat/EntityFramework.DynamicFilters/files/989366/EfDynamicFilter.zip)

It would be very nice, if cou can fix this!

Best Regards,
Xafa

**Comment by Xafa** [comment]
Hi jcachat,

i dont want to bother you, but i am really interested in a solution for this, because this would help us very mutch in our project! So i have a fiew questions:

Could you reproduce it?
Are you working on it?
Do you think you can fix it?
Or do you know a workaround for this?
Can i help you in any way?

Would be nice to hear something from you!
Best regards,
Xafa

**Comment by jcachat** [comment]
Sorry, I have not had a chance to work on this yet.  But I will work on this next.

**Comment by Xafa** [comment]
Hi jcachat,

do you have any new informations to this issue?
Do you think you can solve it in the near future?

Best regards,
Xafa

**Comment by jcachat** [comment]
I am really sorry - I have been swamped with work and life before being gone on vacation (which I am now on).  I was trying to work on this before I left but was not able to.  Part of the problem is that I need to test this with Oracle 12 - which I do not have a license for.  So I need to download and install one of their pre-built developer VM's and have not had time to do that.

I will try my best to work on this when I return next week.

**Comment by jcachat** [comment]
Small amount of progress.  I managed to get Oracle set up and I was able to reproduce the problem with the same project you uploaded.  None of my existing unit tests fail so there is something different in your project that I haven't nailed down yet.

However, while I try to figure out the rest of this, here is a workaround you can do:
1) Pull down the source code for the project from github.
2) Remove your reference to the NuGet package and add in a reference to the EntityFramework.DynamicFilters project.
3) Change the DynamicFilterQueryVisitorCSpace.DoesNotSupportElementMethod() method to always return false.

That disables some special handling for Oracle to work around an issue with older versions (see comments there for info).  It seems that this has been fixed in Oracle 12c and that workaround is not necessary any more.  Your sample project and all unit tests pass with that change.  

I will need to do some testing on different versions of Oracle to figure out the best solution for everyone.  But in the meantime, you can use this method to get everything working for you.

**Comment by Xafa** [comment]
Thank you very much for your efforts!

I am on vacation now, so i will try your workaround next week.
I will tell you then if this works for our project.

Again, thank you for your efforts and your great work.

Best regards,
Xafa

**Comment by jcachat** [comment]
So the problem is that the changes made for v2 of this library enabled creating filters on child properties - like the filter you are creating.  That was done by changing the expression visitor to visit the CSpace expression instead of SSpace (because CSpace gives us access to the child properties).

However, Oracle 11g (which is what I was using to test at the time - because it's the only version of Oracle Express available) does not support the EF Element() method.  And that is needed in order to build the queries for the child property tables.

To work around the lack of support for Element() in Oracle 11, the best I could do was to make it use the old SSpace expression visitor.  And that does not support the child property filters which is the exception you were seeing.

Now that Oracle 12 does support it, I was able to enable everything properly for Oracle 12+.  So it will now build child property filters like it does for SQL Server.  Oracle 11 will continue to throw an exception as there is nothing I can do to fix that.

The fix for this is checked in.  I'll get a new build pushed out in a few days (going to try to knock out a couple more issues).

**Comment by jcachat** [comment]
Build 2.8 has been pushed out to NuGet with this fix.  Let me know how that works.
