### ISSUE TITLE
DB First support

### ISSUE THREAD

**Issue by Boolish** [jcachat/EntityFramework.DynamicFilters#12]
Dear jcachat,

"Access to DynamicFilters is done via extension methods in the EntityFramework.DynamicFilters namespace on the DbContext and DbModelBuilder classes."

OnModelCreating is called only once at CodeFirst stategy.

What if someone would like to use this filter with Database First strategy?

Bests,
Boolish

**Comment by jcachat** [comment]
The filters are configured by adding Conventions into the model configuration (see here for info on Conventions: https://msdn.microsoft.com/en-us/data/dn469439.aspx).  This allows us to add annotations to each table in the model configuration that the filter applies to.  Then when building the query, we can read those annotations to get the filter for it.

Unfortunately, when using Database First, we do not have access to the model configuration at all so it's not possible to create those annotations.

It may be possible to store the filters into a static collection instead of table annotations.  But, it would then be much more difficult to manage the filters by DbContext and to retrieve them during query caching.

At least for the moment, I'm going to say Database First is not supported.  But, I'll leave this issue open  and continue to give it some thought.  And if other people see it and also have the need, please post a "me too" so I can judge how badly it's needed.  If there is a big enough need, I'll find a way to make it happen.

**Comment by Boolish** [comment]
Thank you for the answer I will follow the releases.
B.
