### ISSUE TITLE
Can I dynamically provide the primary key column as the filtered property?

### ISSUE THREAD

**Issue by wbraun** [jcachat/EntityFramework.DynamicFilters#18]
Really cool project!  

I'm working on an authorization app and I would love to use these filters to do row level security. In your examples, you show how you can use a delegate/func to provide a list of values to filter against.  Do you think this approach can also provide the primary key column as the filtered property?  Assume each entity has only one primary key of type int.

It would be cool to not need to create filters for every entity whose rows I want to secure.  I was thinking this may be possible by implementing a function that returns the primary key value for the entity, but I'm not sure. The filter below my help you understand what I'm trying to achieve.

modelBuilder.Filter("FilterByPK", (IFilterByPrimaryKey m, List<int> valueList) => valueList.Contains( GetAuthorizedPrimaryKeyValues(m) ),true);

**Comment by jcachat** [comment]
Sorry, but I don't think there is a way to do what you're asking.

The filter expression (where you have your Contains()) is compiled by EF the first time it's executed.  When that happens, all we're really doing is converting that lambda expression into an EF DbExpression that contains parameter references (in this case to "valueList").  It does not actually get executed or return any values.  And that conversion will not know how to handle external functions like your GetAuthorizedPrimaryKeyValues() method as there is no way to convert that into an EF DbExpression.

When the SQL statement is executed, we intercept it and provide values for the parameters that were created into the DbExpression when it was compiled.  Those values are provided by the last parameters of the Filter() method - in your example, that's "true" (which is obviously not valid for a List).  And during the interception, there isn't even a specific Table Name I could provide since all I have is a SQL statement and the table being filtered could be one of many tables referenced in that statement.

I know it's not as clean and you're trying to avoid this, but I think your only option is to create a filter on every entity like this:
```
modelBuilder.Filter("FilterByPK", (Entity1 m, List valueList) => valueList.Contains(m.ID), () => GetAuthorizedPrimaryKeyValuesForEntity1());
```
