### ISSUE TITLE
Problem with working Effort.EF6.

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#28]
Hi,

I've problems with Effort combined EntityFramework.DynamicFilters.
I shared the code and informations here:
https://gist.github.com/hikalkan/17457ec9c972e4d2a333

Can you check it?

Thanks.

**Comment by hikalkan** [comment]
I also added issue to Effort since I don't know what causes the problem: https://github.com/tamasflamich/effort/issues/11
Both libraries are good and I want to use them together. Please check the problem.

**Comment by jcachat** [comment]
This weekend I will set up a project with the source of both projects and see exactly what's going on.  

But, from the stack trace and other information you put in your gist, I'm going to guess that it's because both libraries are intercepting the sql db commands and are probably interfering with each other.  In my case, I intercept the sql and replace & set parameter values for the filter parameters.  It may be that Effort is intercepting before I am and thus it does not have the parameter values yet - the stack trace seems to suggest something parameter related.  I don't think there is any way to control who intercepts first but it may be based on who registers for the event first so maybe there is something that can be done there.

btw, EntityFramework.Filters (jbogard's project) does not intercept sql like I do which is why that works in this case.  The interception I do is necessary to set parameter values at query EXECUTION  time where his project only sets the parameters at query COMPILE time (which only happens once and thus they cannot be changed dynamically at all).  If you never need to change parameter values, then that approach will work fine for you.  But if you do need to change the parameter values (such as for multi-tenancy or if you do sometimes want to query for deleted entities), it will not.

I'll let you know what I find.

**Comment by leddt** [comment]
I experience the same issue and the only workaround I could figure out was to not configure any filter during my unit tests.

For what it's worth it has worked in the past for me. At the start of my project, I was on EF6.1 and the first release of DynamicFilters and it was working nicely.

**Comment by hikalkan** [comment]
Thanks @jcachat I will wait for the results. You can directly download source codes (https://www.dropbox.com/s/6jllfn0hfprb5gc/EffortDynamicFiltersTest.zip?dl=0) and run it.

@leddt It is not good to disable filters in tests. It will not be a realistic test so. Thanks.

**Comment by jcachat** [comment]
Found the problem.  The non-lambda filter was setting the type of the "is disabled" parameter to a "bool" instead of a "bool?" on the IsNull check.  That was causing Effort to translate it incorrectly.

The fix is pushed and NuGet is updated.

That looks like a pretty useful tool.  I'm going to look into it more for my own use.  If you find any other problems, create an issue for it and I'll check it out.

**Comment by hikalkan** [comment]
Thank you so much. I'll update and check it.
BTW, I've an article on unit testing with Effort and ASP.NET Boilerplate: http://www.codeproject.com/Articles/871786/Unit-testing-in-Csharp-using-xUnit-Entity-Framewor

I it works, I'll close the issue.
