### ISSUE TITLE
Filter restrictions

### ISSUE THREAD

**Issue by jwillmer** [jcachat/EntityFramework.DynamicFilters#35]
This is more a question then an issue:
I added an global (interface) filter that filters all entrys for a specific companyId. I also added this filter to my user table but as it turns out the aspnet identity provider needs the full table scope to find the right user to login and I can't really add filter disable rules into the framework.
Is there another posibillity to disable filters for framework code or something like that? any ideas?
I thought about a second db connection but I have to eval first if this is possible..

**Comment by jwillmer** [comment]
Solved with a second dbContext without filters: [stackoverflow](http://stackoverflow.com/questions/11197754/entity-framework-one-database-multiple-dbcontexts-is-this-a-bad-idea)

**Comment by cindoum** [comment]
Is there any way to exclude some queries? I am facing the exact same issues but i dont want to manage 2 contexts... 

I previously used EntityFramework.filters (moved because of the caching issue) and that used to work. When using the userManager, the query was not filtered so i was able to login...
