### ISSUE TITLE
DatabaseFirst 

### ISSUE THREAD

**Issue by chadash** [jcachat/EntityFramework.DynamicFilters#41]
thanks a lot for your effort! Jcachat.
it is possible to use this solution with DatabaseFirst (EDMX) Approach?

**Comment by jcachat** [comment]
Sorry, but when using Database First, we don't have any access to the model configuration so this is not supported.

**Comment by chadash** [comment]
Special thanks for the speed of the response...
do we have nothing to do on the constructor of the class who inherit from DbContext ?
i see that is possible to adding a "System.Data.Entity.Infrastructure.Interception.DbInterception.Add(...)" on the constructor.
It does not help?
thanks again, chadash

**Comment by jcachat** [comment]
There is nothing on the constructor to help with this.

The configuration of the filter requires access to the DbModelBuilder object so that we can store information about the filter into the EF EntitySets that are built from the model (using Conventions to add attributes to the Metadata).  When using Code First, we can do that in OnModelCreating - which allows us to customize the model configuration.  Using Database First, all of the model configuration is done via the loading of the EDMX and EF does not give us any chance to do any further customization.

It might be possible to find another way to inject the filter information.  But, it's much more complicated (but not impossible) to translate .Net Clr types into the EF EntitySets to then add the filter configuration.

I'll keep this issue open and give it some more thought.  Hopefully I can come up with something.
