### ISSUE TITLE
What LINQ methods do NOT work (SQL Server)

### ISSUE THREAD

**Issue by neal007** [jcachat/EntityFramework.DynamicFilters#46]
Hello,

Great tool - thank you for this!  I'm using this to filter data by UserId (INT) as our SQL SERVER 2014 database supports multi-user, each table has a UserId column (and a second primary key column as well).  I had a little issue yesterday where I believe using the LINQ Find() extension where I removed the check for UserId and just checking for the secondary key failed.  For example I used to use entity.Find(userId, entityId) and since applying the DynamicFilters I figured the userId part was no longer needed.  I believe this is the cause of my error in that the Find() method still needs both primary keys in the composite key?

If there is a list of info on when dynamic filters can work vs. when they cannot be applied I'd appreciate it so I don't expect that it's filtering for me when in fact it's not.

Thank you

**Comment by jcachat** [comment]
You can use these filters in place of any conditions that you would normally put into a .Where() clause of an IQueryable<T>.

I actually never even considered how (or if) the filters are applied when using Find().  EF may build that query much differently since it doesn't support any linq conditions.  I'll need to try this out and see what happens.

Can you post the error you got?  If it's about multiple rows being returned by Find(), then that would tell me the dynamic filters are not being applied (which is not good).  Otherwise, it may just be that EF saw that you have a composite key and did not provide both values.  It would probably figure that out as it's building the query internally - before we even have a chance to add our conditions.

**Comment by neal007** [comment]
I don't have any errors to share.  I got a few error notification emails from my WCF service regarding primary key conflicts so I reverted a change in one critical file.  It just makes me think the Find method where primary keys are passed are not filtered.  Not a big deal, just wanted to learn when/where I can use the dynamic filters reliably.  Thanks again.
