### ISSUE TITLE
Ninject loses scope in filter method

### ISSUE THREAD

**Issue by themephs** [jcachat/EntityFramework.DynamicFilters#50]
I ran into an issue concerning using dependency injection (Ninject) with a dynamic filter.  Here are the parameters of the problem:

1.  SystemContext (extension of DbContextBase -> DbContext), using a Ninject binding in "request" scope, which means the instance of the context is maintained for the lifetime of the HTTP request.  So if I change the property "CurrentPartitionKey" on the instance, it should have the same value on the instance of SystemContext until the HTTP request ends.

2.  CurrentPartitionKey is changed based on the user's key when the SystemContext is created.

3.  I have the following filter:

```c#
mb.Filter("FilterPartition", (IPartitioned item, long? userKey, long bitMask) => {
     (!userKey.HasValue || !item.PartitionKey.HasValue || ((item.PartitionKey & bitMask) == userKey))
},
() => CurrentPartitionKey,
() => PartitionHelper.GetComparisonMask(CurrentPartitionKey)
```

4.  When I check the context property values while debugging, CurrentPartitionKey is 2, everywhere while stepping through the code... however when the filter is triggered from a Db query, CurrentPartitionKey is now NULL.  When it exits the scope of the function where it retrieves CurrentPartitionKey, it is 2 again.

Is this intended behavior or does the filter contain a seperate instance of my DbContext class?  Does it have a problem working alongside an IoC container that manages the context in the request scope?

I think I have a workaround by setting the argument values in the function (userKey and bitMask) via this.SetFilterScopeValue.

Please let me know if you have any insight into this, and if it is an issue or intended behavior?

**Comment by jcachat** [comment]
I think what's happening is that when the function for "() => CurrentPartitionKey" is evaluated, "this" will be referring to the SystemContext/DbContext of the instance where OnModelCreating was called.  That's just how the scoping will work for the delegate.  So there won't be a way to access values/methods on the currently executing DbContext instance.  

I do something similar (and also use Ninject) but the property I access is actually static and returns my "current user information" from data that I've stashed into Thread.CurrentPrincipal when the web request comes in.  Maybe you could do something like that instead of storing it into your SystemContext instance?

**Comment by themephs** [comment]
That probably would work but I'm avoiding using statics in the context.  The partition can be changed by root users to emulate a customer view and I'm just setting the scope value to the partition key instead and that works fine (using the SetFilterScopeParameter ext method)

**Comment by jcachat** [comment]
Yes, SetFilterScopeParameter sounds like a better way to do it.  Didn't even think of that and missed that in your first post.

It might be possible to pass the DbContext as a parameter to that delegate but it may be a little difficult to get in the right place and may be a breaking change.  I think what you're doing is probably the best way to handle it at this point.
