### ISSUE TITLE
25VU load test shows that a very same query had different table alias

### ISSUE THREAD

**Issue by tiwariarvin** [jcachat/EntityFramework.DynamicFilters#66]
Hi -

When running 25VU load test, I realized that the a **very same query** had different alias for very same table. In the query copied below, please realize that we encountered "Var_291" (as in code below) and "Var_252" and few others as well for a query though all of the query parameters are also same. 

`FROM (SELECT [Var_291].[SomeColumn] AS [SomeAlias],`
`[Var_291].[SomeColumn] AS [SomeAlias]`
`FROM [SomeTable1] AS **[Var_291]**`
`WHERE ([Var_291].[IsDeleted] = @DynamicFilterParam_000003) ) AS [Extent1]`

Can someone help me fix this?

This is important as it creates multiple "cache" for exactly same queries, this affects performance and we really need to resolve the same.

**Comment by jcachat** [comment]
The EF internals decide when to compile a query or use a cached version of it.  There is nothing we can do about that in the Dynamic Filters.  And that would not be happening because of the filters we are adding.

If this only happens during a load test, I would suspect EF just doesn't do thread synchronization around the process or looking up a cached query and compiling it if it doesn't exist.  And that's probably necessary for performance so that you don't have query compilations (which are normally different than each other and expensive to do) from blocking other queries from executing.

Try changing your queries to not use Dynamic Filters and repeat your load test.  Make sure they have the same IsDeleted condition in a .Where() clause.  You should see the same thing happening.

If you see different results, then I would need you to post some code that demonstrates it.

**Comment by tiwariarvin** [comment]
Thanks @jcachat for your reply, I should be able to put a sample somewhere by mid this month.
