### ISSUE TITLE
Option to turn off Navigation Property Filter

### ISSUE THREAD

**Issue by cavinlee** [jcachat/EntityFramework.DynamicFilters#68]
Hi, 
May i know how do I apply filter ONLY on the Model and not the rest of the Navigation from the Model?
Reason being that all my Model are partitioned.

Filter on the parent will be sufficient.

**Comment by jcachat** [comment]
There is no option to not apply filters to the navigation properties.  Can you give me a more specific example of how you have your model (with child properties) defined and the filter(s) you are using.  I would like to better understand what you are trying to accomplish to see how or if it can be handled.

**Comment by cavinlee** [comment]
I checked the query generated in SQL Profiler and the filter goes to every single navigation property that i have.

I have an interface that does the data partition and it applies to all entity/model that I have.

Example
`public class Stuff : ISeparateByPartition
{
    public virtual int **PartitionId** {get;set;}
    public virtual int Id {get;set;}
    public virtual string Name {get;set;}
    public virtual Customer Customer {get;set;}
    public virtual User User {get;set;}
}
public class Customer : ISeparateByPartition
{
    public virtual int **PartitionId** {get;set;}
    public virtual int Id {get;set;}
    public virtual string Name {get;set;}
}

public class User : ISeparateByPartition
{
    public virtual int **PartitionId** {get;set;}
    public virtual int Id {get;set;}
    public virtual string Name {get;set;}
}

modelBuilder.Filter("PartitionFilter", 
    (ISeparateByPartition entity, int partitionId) => 
    entity.PartitionId == partitionId, 
    MyContext myContext) => myContext.PartitionId);`

The DynamicParamater apply to every model when i query Stuff data.

**Comment by jcachat** [comment]
Since you are defining the filter on the ISeparateByPartition interface and all of those classes implement that interface, that is how it's supposed to work.  If you only want that to apply the filter to your "Stuff" model, define it only on that class like this:
```
modelBuilder.Filter("PartitionFilter", (Stuff entity, int partitionId) => entity.PartitionId == partitionId, (MyContext myContext) => myContext.PartitionId);
```

**Comment by cavinlee** [comment]
Customer has its own usage and able to run by itself too, which also being partitioned.
So I'm looking for it to be able to apply to the direct model I'm querying from only. 
Else, the query generated is too much.

Thought?

**Comment by jcachat** [comment]
Sorry, I don't have a solution for this at the moment.  But now that I think about it more, I probably hit this same situation in my own app (joining 2 entities that both have a "tenant ID" would duplicate the condition that is not needed due to the inner join).  I can see how it would be worthwhile to eliminate the extra conditions.  

I'll give it some thought and see what I can come up with.

**Comment by cavinlee** [comment]
thanks you.

**Comment by spgoad** [comment]
Hey all - I'm curious where you landed on this particular issue. We are using this project to handle multi-tenancy (thanks @jcachat!), and I started realizing this was something of a problem when some legacy code made far too much use of navigation properties. The code would traverse 4-5 levels of navigation, several times in a single query - which meant our output became something like 500+ lines of SQL with tons of sub queries instead of the simple 40 or so lines it would be if we just joined each sub table with out the filter.

I forked this repo this morning and took a stab at implementing this option just to see if it was possible - and I think I've got a working approach at least in the CSpace realm. I changed Visit(DbPropertyExpression) so when it finds a navigation property to filter it first checks the DeclaringType (essentially the parent class) to see if the same filter applied there. If the filter would apply to the parent and a new boolean option (FilterNavigationProperties) on the FilterDefinition is set to false, it doesn't apply the filter to the sub record.

I'm not terribly familiar with the inner workings of expressions and EF, so if I missed something in this approach I definitely welcome feedback. I haven't added tests around it or checked other Visitors or DB types yet (I really only have access to MS SQL), so the fork isn't ready for a pull request, but I wanted to go ahead and post and see specifically where you may have last left this idea @jcachat.

**Comment by jcachat** [comment]
Sorry, I got busy and completely forgot about this issue!  ...and a few others.  I've been trying to go back and catch up on some of them over the past week but missed this one.

What I was thinking about doing is adding an option to the filter definition to control how (or if) filters are applied to child properties.

We can't completely disable applying the filters to the navigation properties as it will break situations where you DO want them applied.  i.e. an ISoftDelete filter that should always be applied to everything.

I'll try to get this worked in soon.  In the meantime, feel free to do what you need to do with the source to get it to work for you.

**Comment by spgoad** [comment]
No worries - we just came across this ourselves. I definitely agree that you can't turn off navigation property filtering in all circumstances - that's why I went with the option on the filter definition just as it sounds like you were thinking. Feel free to check out my commit to the fork earlier today if you'd like to see what I did - https://github.com/spgoad/EntityFramework.DynamicFilters/commit/76cb6975fe5a7338a05a32c02ac0ad73623e3681

If you don't like the approach, no problem, but if it is close to what you are thinking I'd be glad to work on polishing it up and creating a pull request. Thanks!

**Comment by MehdiSaeedifar** [comment]
any progress? i have the same issue.

**Comment by spgoad** [comment]
We've been using my fork of this repo, and I haven't revisited adding tests and creating a pull-request into the main repo. You're welcome to take a look at my fork though - it's been working well for us so far.

**Comment by MehdiSaeedifar** [comment]
@spgoad  Thanks.

**Comment by jcachat** [comment]
Sorry for the delay.  I am finally working on this right now.  Here is what I'm doing:

You may have noticed that the Filter() method has a parameter on it called "selectEntityTypeCondition"  That was done for #70 which you can read about there.  It is somewhat similar to this issue except that it affects which entities a filter gets applied to - it does not affect how/if a filter is applied to the child properties.

I am replacing that parameter (which will be a breaking change if anyone other than me happens to be using it) with an "options" parameter.  This will be more flexible and will allow adding additional filter options over time - without having to add (yet more) parameters to all of those Filter() methods.  It will be a fluent-style parameter ("options -> options.SetSomething().SetSomethingElse()" ).  Initially, it will have the "SelectEntityTypeCondition".

These are the additional options I am thinking about putting in there right now to handle the issues here and to try to allow the filter creator to prevent the filter from being over applied (and creating massive sql statements):
"ApplyToChildProperties": If false, the filter will not be applied to child properties.
"ApplyRecursively": If false, the filter will not be applied recursively (i.e. if it was applied to the parent do not apply again).

All options will default to how it works now so existing queries are not affected - which is to apply the filters all over the place.

Any thoughts on this before I get too deep into it?  Will this cover the issues you are all having?  Need more options?

**Comment by MehdiSaeedifar** [comment]
@jcachat 
It is exactly what we want. we want query filtering just on root query. In our system, most of the queries contains more than 30 joins and now with this filtering library we get sql server timeout because of massive complex query generated by the filter on child entities.

**Comment by spgoad** [comment]
I think that would work well - I like the idea of the options parameter instead of adding additional filter parameters for each new thing. That was one of the more difficult parts of adding the option that I did in my fork, but ultimately gets to the exact same end result.

**Comment by MehdiSaeedifar** [comment]
@spgoad  I'm using your fork, but still there is no difference between queries generated by original library.
Any idea?

**Comment by spgoad** [comment]
@MehdiSaeedifar Did you set the filterNavigationProperties value to false when defining your filter? Example - modelBuilder.Filter("TenantID", (TenantEntity e) => e.TenantID, (ApplicationDbContext context) => context.TenantID, false);

**Comment by MehdiSaeedifar** [comment]
@spgoad Yes, i'm pretty sure.

**Comment by jcachat** [comment]
I just pushed out an update (v 2.9) to NuGet that has these new options added.  The main readme has been updated to include them.  See here: https://github.com/jcachat/EntityFramework.DynamicFilters#filter-options.

Please let me know how this works for all of you when you get a chance to update to it.
