### ISSUE TITLE
Use cases requires Filter to change on the Cached Model

### ISSUE THREAD

**Issue by fallenfate1982** [jcachat/EntityFramework.DynamicFilters#79]
I'm not sure this is the correct place to get help like this, but it was the only area I found. Apologies in advance if this is the incorrect place.

Bascially I have the filters in the OnModelCreating method and this works fine. I do however, need to change that filter based on the user logged in. I can't use the feature for scopped filters given this use case and application arch. I've been trying to force the running of the OnModelCreating when a different user logs in. However, I haven't gotten this to work.

Is there a way to adjust the global value of the filter after OnModelCreating was run?

**Comment by jcachat** [comment]
It's not possible to define or change the filters other than inside OnModelCreating.  And OnModelCreating is called exactly once - on application start - and there is no way to alter that.  

Also, EF compiles each distinct query once (on first execution of that query) so we only have 1 opportunity to inject our filters.  Once the query is compiled, it is locked in place and can't be changed.  We have to dynamically alter the parameters of our filters by intercepting the SQL commands but otherwise can't alter the conditions in the filters.

I don't know how complex your query differences are, but the best option might be to try create a single query that has a parameter on the parts that differ and change that parameter based on your current user.

**Comment by fallenfate1982** [comment]
Thanks for the information. Your suggestion sounds like what I want to do, but I'm not sure how to do it. 

Can you correct me in the following approach. Using the example from the documentation:

modelBuilder.Filter("Notes_CurrentUser", (Note n) => n.PersonID, () => GetPersonIDFromPrincipal(Thread.CurrentPrincipal));

Based on what you are saying I'm assuming GetPersonIDFromPrincipal Is a delegate I can have anywhere in my solution and if I change the value it returns dynamically, it will also change the filtering in the global context. So for instance during running I changed values that then made GetPersonIDFromPrincipal return 5, all data will now be be where PersonID is 5 instead of what it was when the application initially started?

**Comment by jcachat** [comment]
That's correct.  But in the example, GetPersonIDFromPrincipal() is actually a method in the context class.  But, you can put it anywhere you want (if it's static).  Or it can be a non-static method in your context class as described here: https://github.com/jcachat/EntityFramework.DynamicFilters#parameter-expressions
