### ISSUE TITLE
Filters based on Interfaces only work for implicit implementation

### ISSUE THREAD

**Issue by Relic79** [jcachat/EntityFramework.DynamicFilters#8]
When using interface based filters in VB.Net, if the interface property has a different name than the property in the object implementing it, the filter is not applied. For example
```
public interface IBlogPost
	Property PrimaryKey as long
end interface

public class BlogPost
	implements IBlogPost
	public property ID as Long Implements IBlogPost.PrimaryKey
end class
```
If a filter for IBlogPost is defined, it will not be applied.

**Comment by Januschan** [comment]
C#

public interface IBlogPost
{
      long PrimaryKey { get; set; }
}

public class BlogPost : IBlogPost
{
     //this is what VB does under the hood with 'implements' as described in the example above
      public long ID 
     {
          get { return ((IBlogPost)this).PrimaryKey; }
          set { ((IBlogPost)this).PrimaryKey = value; }
     }
      long IBlogPost.PrimaryKey { get;set;}
}

**Comment by jcachat** [comment]
Thanks Januschan, that's helpful.  Defining a C# class/interface like that, I am able to reproduce the problem.

But, I'm not able to solve it.  The problem is that according to the EF model that is produced by that class, the public property name is "ID", not "PrimaryKey".  So what happens is that I see there is a filter on BlogEntry on the PrimaryKey property.  But then none of the properties in the EF entity have that column so we fail to create the filter (and an exception will be thrown).  There is no way to know that there is code there which is mapping "ID" to "PrimaryKey" in this particular class.

I'm sorry, but I don't see that there is any way this can be supported.  If you want to create a filter against the interface, you will not be able to re-map your properties like this.  Or you will need to create your filter on the entity itself, not the interface.

**Comment by Januschan** [comment]
I think it makes sense not to support this VB compiler trick.  I was just
illustrating what that compiler does, and this info allows VB developers to
explicitly implement the underlying code for it.  C# also has some compiler
trick candy which is not strictly supported by <your .NET lib here>.

~B
