### ISSUE TITLE
Exception when used with SQL Server CE

### ISSUE THREAD

**Issue by RobertSullivanSoftwire** [jcachat/EntityFramework.DynamicFilters#81]
We're seeing an issue with v2.4 and the EF6 SQL Server Compact adapter (v6.13).

Specifically, the fix to #53 manually modifies the CommandText on the DbCommand (see comment on line 903 [here](https://github.com/jcachat/EntityFramework.DynamicFilters/blob/master/src/EntityFramework.DynamicFilters/DynamicFilterExtensions.cs)). Unfortunately, the SQL Server CE adapter throws an exception if the Command text is set directly - see [here](https://github.com/mono/entityframework/blob/70998a4be0ed566ad3f21d6c5a51016b7c16f9bd/src/EntityFramework.SqlServerCompact/SqlCeMultiCommand.cs).

In most cases we can avoid this using modelBuilder.PreventAllDisabledFilterConditions(), but there are some situations where we'd like to disable our filter while using SQL Server CE - for now, we've reverted to v1.4.9 to handle this.

Thanks!

Rob

**Comment by jcachat** [comment]
I could add a check to see if this is running against SQL Server CE and prevent any CommandText changes.  That should effectively prevent what was done for #53 under SL Server CE.

But, if there is a filter that requires modifying the CommandText (such as a filter that uses IEnumerable.Contains() ), we won't be able to build it correctly.  I'll have to throw an exception in those cases.

If this will help, I'll make that change.  I'm guessing since 1.4.9 works for you that it would - at least for the filters you are currently using.

**Comment by RobertSullivanSoftwire** [comment]
Thanks - if you have the chance, I think that would be perfect. I don't think any of our filters modify the CommandText, so it would solve the problem for us, at least :)

**Comment by jcachat** [comment]
Build 2.8 has been pushed out to NuGet with this fix.  Let me know how that works.

For SQL CE, it will never attempt to remove the "filter is disable" claused during sql interception.  That was the change made for #53.

Nothing can be done to support Contains() for SQL CE but I did put a more descriptive exception there to help explain it.
