### ISSUE TITLE
Can someone explain the Migrations that filtering adds

### ISSUE THREAD

**Issue by TehWardy** [jcachat/EntityFramework.DynamicFilters#90]
I recently had this issue ...
https://github.com/jcachat/EntityFramework.DynamicFilters/issues/87

Having solved that I noticed that when I add my filter ot the Pages set I get a migration ...

```
        public override void Up()
        {
            AlterTableAnnotations(
                "dbo.Pages",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        ParentId = c.Int(),
                        Name = c.String(nullable: false),
                        Path = c.String(),
                        Layout = c.String(),
                        Content = c.String(),
                        Script = c.String(),
                    },
                annotations: new Dictionary<string, AnnotationValues>
                {
                    { 
                        "DynamicFilter_Page_PagesForUser",
                        new AnnotationValues(oldValue: null, newValue: "EntityFramework.DynamicFilters.DynamicFilterDefinition")
                    },
                });        
        }
```

What does this do to the Db?
I've never seen this before and don't understand it?

**Comment by jcachat** [comment]
What database are you using?  I think the PostgreSql EF driver does that and it's not something we can control.  It's because the filter configurations are stored as attributes inside the EF model (and that cannot be changed).  For some reason, that EF driver wants to write out the attributes into the database.

Someone else had mentioned this happening in another issue.  There may be more information there - try searching for it.

**Comment by TehWardy** [comment]
MS SQL.
So does it actually change something in the DB?
As long as it's not a structural change it should be ok ... I guess.

I have DB's that I want to manage with dynamic filters but we have an old code base that uses something called LLBLGen in the code (don't ever use it, EF is amazing compared to that mess).
The long and short of it is, in that DB I don't ever want to alter the DB, but I do want to add it to a new code first stack (done by generating the initial model from the db), about all I can do in that DB is add new tables, anything else causes major headaches!

Random question ...
Why do filters need to be added to the model is this how you control the entity creation process with the filter rules?

**Comment by jcachat** [comment]
Now that I look more closely at my own project, I do see that it also has added some of those attributes into some migrations.  We generally just use EF auto migrations and only create manual migrations when absolutely necessary so I just haven't noticed it before.

As far as I know, that doesn't actually write out anything to the database.  But if you're creating migrations in code (as you are actually supposed to be doing), I can see how this could generate some unnecessary confusion.

The filters get attached to the entities like this (as annotations) because it gives a clean and efficient way to store the filter definitions on the entity itself.  Otherwise, we wouldn't have a way to get the configuration or (if we stored it statically) we would have to iterate over all filters - every query compile - to try to figure out which filters apply.  And (it's been a while) I don't think we have the right c# entity needed to figure that out at the time we are compiling the query.

If those annotations do cause issues, let me know.  It might be possible to suppress them during the sql generation process of the db migration.  I have written a custom "SqlServerMigrationSqlGenerator" to do stuff like that before.  But I'm pretty sure, as it is now, nothing is actually output.  You can verify that with sql profiler.

**Comment by TehWardy** [comment]
Thanks Jcachat, further testing hasn't revealed any problems yet so i suspect you are right.

I have a pretty big perf hit on sone queries though but I think that might be my design.

**Comment by precisioninfinity** [comment]
@jcachat Thanks for the QA on this post as we had the same question!  Any chance you hacked out that SqlServerMigrationSqlGenerator file in order to prevent the unnecessary migration and can post it here?

**Comment by jcachat** [comment]
Sorry, no.  It wasn't causing any problems in our project so didn't bother trying to suppress it.

**Comment by Worthy7** [comment]
@jcachat Hey man, I've been struggling with this for 2 days now. It seems that this is causing a big problem in the oracle provider - just having any `AlterTableAnnotations` in a migration: throws  :
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.Generate(System.Data.Entity.Migrations.Model.CreateTableOperation)' has some invalid arguments
```

Would you mind explaining what exactly Entity Annotations are? I can't wrap my head around it and everything I search for tries to give me things related to EF DataAnnotations (on classes etc).

I am on the old EF6, using DF 2.10 (I can't upgrade because of stuff.)
