### ISSUE TITLE
Excluding dynamic filter for some entities

### ISSUE THREAD

**Issue by yogeshexcel** [jcachat/EntityFramework.DynamicFilters#92]
We are using DynamicFilter for excluding "IsDeleted" columns in our entities like this -

`modelBuilder.Filter("IsDeleted", (MyAppEntity d) => d.IsDeleted,false);`

Here `MyAppEntity`  is our base entity for all our entities.

And it is working perfectly fine.

However, we want to exclude this filter for a few entities. We have tried the following statement, but it is not working - (I am trying to exclude "Contact" entity for example)
`modelBuilder.Filter("IsDeleted", (MyAppEntity d) => d.IsDeleted && d.GetType() != typeof(Contact), false);`

One other option could be to apply this filter specifically for each entity, but that would made it difficult to manage entities.

Can you please suggest how I can exclude some entities from the filter please?

**Comment by jcachat** [comment]
"GetType()" will not work inside a filter because that is a linq/c#/.Net function - it is not a function that is translatable to SQL.

You have 2 options to accomplish what you are trying to do:
1) You can enable/disable the filters as needed before you execute the query.  See here: https://github.com/jcachat/EntityFramework.DynamicFilters#enabling-and-disabling-filters
2) You can specify a condition to evaluate (in which you CAN use that GetType() method) as described here: https://github.com/jcachat/EntityFramework.DynamicFilters#conditionally-enabling-filters
